### ISSUE TITLE
Why do we choose PyText

### ISSUE THREAD

**Issue by applenob** [microsoft/dstc8-meta-dialog#10]
Hi,

I am new to `pytorch`. And when I try to implement the dialogue generation model using this `pytext` structure I found it's hard. 

Facebook has `pytext` and `fairseq` both based on `pytorch` with `fairseq` focusing on machine translation and summary tasks while `pytext` focusing on other types of tasks. So there are lots of demo code for text generation model written by `pytorch` or `fairseq` but almost nothing by `pytext`. I tried to transform the code from `pytorch` to `pytext` and found it's not easy for the `decode` part.

Do you have any suggestions for implementing the dialogue generation model? Should I only use your `data_handler` and write the model from scratch with `pytorch`?

Thank you!

**Comment by aatkinson** [comment]
We initially chose PyText for it's modularity, library of reusable components, integration with torchtext, and the PyText base config (which makes it easy to serialize object parameters and hierarchies to JSON and instantiate from it). 

We have encountered similar issues with PyText; we also note that this project is dependent on an older version so APIs may not line up. 

You can make a PyText-compatible model using fairseq and vanilla PyTorch, but some parts are tricky, and we don't have an example ready to share at this time.

Gutting the `data_handler` and it's dependencies from `mldc/preprocessing`, then implementing your model however you like is a convenient option. Another advantage is we overrode most of PyText's data handler and featurizer utilities, and extended them for this project, so most of the logic you need to dissect is right here in this repo.

**Comment by applenob** [comment]
Thank you for your reply and suggestion.
