### ISSUE TITLE
About the baseline result

### ISSUE THREAD

**Issue by shuaihuaiyi** [microsoft/dstc8-meta-dialog#5]
I tried the scripts in README, and this is my result:

Bleu_1 | Bleu_2 | Bleu_3 | Bleu_4 | CIDEr | METEOR | ROUGE_L
-- | -- | -- | -- | -- | -- | --
0.0477763 | 0.0160963 | 0.0063228 | 5.14E-07 | 0.0407825 | 0.0452248 | 0.0432814

Is that correct? Or did I make some mistake in the procedure?

**Comment by yana-xuyan** [comment]
I also tried the same procedure and got similar results...

**Comment by aatkinson** [comment]
We have similar results as well, these are correct.
The retrieval baselines aren't necessarily high-quality, but illustrate a simple retrieval approach and demonstrate its effectiveness.

Out of curiosity, may I ask which domain these results are for - or are they the average of all domains in MetaLWOz?

**Comment by shuaihuaiyi** [comment]
> We have similar results as well, these are correct.
> The retrieval baselines aren't necessarily high-quality, but illustrate a simple retrieval approach and demonstrate its effectiveness.
> 
> Out of curiosity, may I ask which domain these results are for - or are they the average of all domains in MetaLWOz?

These results are for EVENT_RESERVE only, as the scripts in README only predict this domain. I didn't change anything except remove the  `[other test domains...]` statement of evaluate command.
