### ISSUE TITLE
A small bug in the starting code

### ISSUE THREAD

**Issue by yana-xuyan** [microsoft/dstc8-meta-dialog#6]
Dear organizers,

I found a small bug, or in other words, a typo in the offered starting code. In the ["mldc/task/retrieval.py"](https://github.com/microsoft/dstc8-meta-dialog/blob/master/mldc/task/retrieval.py), an attribute error (AttributeError: 'NoneType' object has no attribute 'close') will be caused by the code in line 110 and 111.
`if self.model_needs_meta_training:
        train_iter = self.data_handler.get_train_iter(
          stack.enter_context(closing(train_iter)))`

The right code should be:
`if self.model_needs_meta_training:
        train_iter = self.data_handler.get_train_iter()
        stack.enter_context(closing(train_iter))`

**Comment by aatkinson** [comment]
thanks! I've fixed it in https://github.com/microsoft/dstc8-meta-dialog/pull/7/
